import {
  Zap,
  Wind,
  Sun,
  Star,
  Snowflake,
  Flame,
  UtensilsCrossed,
  MapPin,
  Hotel,
  Cigarette,
  BriefcaseBusiness,
  Swords,
  Ruler,
  Pencil,
  Paintbrush,
  Hammer,
  CalendarDays,
  Hourglass,
  CalendarFold,
  Clock,
  Hash,
  CircleHelp,
  TreePalm,
  Leaf,
  Recycle,
  Award,
  Trophy,
  ThumbsUp,
  ThumbsDown,
  Sticker,
  Heart,
  CakeSlice,
  BadgeDollarSign,
  ShoppingCart,
  ShoppingBasket,
  Shield,
  KeyRound,
  Fingerprint,
  Telescope,
  Atom,
  Brain,
  Palette,
  Eye,
  EyeOff,
  Album,
  Image,
  Baby,
  PersonStanding,
  Navigation,
  Globe,
  MountainSnow,
  Popcorn,
  Music,
  Film,
  Clapperboard,
  Drama,
  WalletMinimal,
  Landmark,
  Pill,
  Skull,
  Ghost,
  Crown,
  Gamepad,
  Cookie,
  Sandwich,
  Martini,
  CupSoda,
  Coffee,
  Apple,
  ChefHat,
  Carrot,
  Videotape,
  Smile,
  Frown,
  Annoyed,
  Angry,
  HeartCrack,
  Puzzle,
  Gem,
  Rabbit,
  Bird,
  Turtle,
  Moon,
  UsersRound,
  type LucideIcon,
} from 'lucide-react';

const TAG_ICONS: Record<string, LucideIcon> = {
  // Art
  Palette: Palette,
  Paintbrush: Paintbrush,
  Pencil: Pencil,
  Music: Music,
  Album: Album,
  Videotape: Videotape,
  Film: Film,
  Popcorn: Popcorn,
  Drama: Drama,
  Image: Image,
  Clapperboard: Clapperboard,
  Trophy: Trophy,
  Award: Award,

  // Games
  Gamepad: Gamepad,
  KeyRound: KeyRound,

  // Emoji
  UsersRound: UsersRound,
  Baby: Baby,
  PersonStanding: PersonStanding,
  Smile: Smile,
  Frown: Frown,
  Annoyed: Annoyed,
  Angry: Angry,
  ThumbsUp: ThumbsUp,
  ThumbsDown: ThumbsDown,
  Heart: Heart,
  HeartCrack: HeartCrack,
  Eye: Eye,
  EyeOff: EyeOff,

  // Other
  CircleHelp: CircleHelp,
  Hash: Hash,
  Sticker: Sticker,
  Recycle: Recycle,
  Puzzle: Puzzle,

  // Nature
  TreePalm: TreePalm,
  Leaf: Leaf,
  Sun: Sun,
  Moon: Moon,
  Snowflake: Snowflake,
  Wind: Wind,
  Flame: Flame,
  Zap: Zap,
  Star: Star,
  MountainSnow: MountainSnow,

  // Food
  UtensilsCrossed: UtensilsCrossed,
  ChefHat: ChefHat,
  Coffee: Coffee,
  CupSoda: CupSoda,
  Martini: Martini,
  Apple: Apple,
  Carrot: Carrot,
  Sandwich: Sandwich,
  CakeSlice: CakeSlice,
  Cookie: Cookie,

  // Animals
  Rabbit: Rabbit,
  Bird: Bird,
  Turtle: Turtle,

  // Castle
  Ghost: Ghost,
  Skull: Skull,
  Crown: Crown,
  Gem: Gem,
  Shield: Shield,
  Swords: Swords,

  // Science
  Atom: Atom,
  Telescope: Telescope,
  Brain: Brain,
  Pill: Pill,
  Fingerprint: Fingerprint,
  Cigarette: Cigarette,
  Ruler: Ruler,
  Hammer: Hammer,

  // Travel
  Hotel: Hotel,
  Landmark: Landmark,
  Navigation: Navigation,
  Globe: Globe,
  MapPin: MapPin,
  CalendarDays: CalendarDays,
  CalendarFold: CalendarFold,
  Clock: Clock,
  Hourglass: Hourglass,

  // Finance
  BadgeDollarSign: BadgeDollarSign,
  ShoppingCart: ShoppingCart,
  ShoppingBasket: ShoppingBasket,
  WalletMinimal: WalletMinimal,
  BriefcaseBusiness: BriefcaseBusiness,
};

// const TAG_ICONS_MAP: Record<string, LucideIcon> = TAG_ICONS.

export { TAG_ICONS };
